### ISSUE TITLE
Integrate with Timber 2.0

### ISSUE THREAD

**Issue by acobster** [sitecrafting/conifer#131]
Just an ongoing grab-bag issue to resolve changes needed to switch to Timber 2.0.

**Comment by rhendrickson-sc** [comment]
@sdunham Can we close this issue considering Conifer 1.0 has been released and is using Timber 2?

[Link to composer.json line](https://github.com/sitecrafting/conifer/blob/f2cf093c6d2220b378d0ad7716b03d2fd3ba62d2/composer.json#L24)

**Comment by sdunham** [comment]
Yep, this can be closed out!
