### ISSUE TITLE
Update Post::create to initialize instances the way Timber 2.0 expects

### ISSUE THREAD

**Issue by sdunham** [sitecrafting/conifer#144]
https://github.com/sitecrafting/conifer/blob/ed2f07db2c8ff0769218df5f71ee0f835f9f4870/lib/Conifer/Post/Post.php#L360

`Post::create` initializes the posts is creates by instantiating the class directly, but Timber 2.0 expects you to use `Timber::get_post`

**Comment by acobster** [comment]
already fixed in the [timber-2.x](https://github.com/sitecrafting/conifer/pull/135/files#diff-07b20cbba80d6654264c777229d6d928103371ee8a095b0b46d7e8d67f9a4d89) branch/PR.
