### ISSUE TITLE
DOCUMENT ALL THE THINGS

### ISSUE THREAD

**Issue by acobster** [sitecrafting/conifer#32]
Just a running list of things we should document before considering this ready for BETA.

Features

- [x] What is Conifer?
- [x] Why would I use it
- [x] Values
- [x] Testing
- [x] CHANGELOG
- [x] Contributing (PR template)
- [x] Issue template
- [x] Installation
- [x] Getting Started
- [x] The Site Class
- [x] Post classes - out-of-the-box post types, why `Post` is abstract, how to do CPTs
- [x] AjaxHandler - basic & advanced use-cases (see doc comments in AjaxHandler.php)
- [x] Forms - how to set up a basic form with validations
- [x] Admin helper API
- [ ] Integrations (Yoast, Google?)
- [ ] ~~Navigation (menu item abstractions)~~ -PRs in Timber 2.x will address this
- [x] Shortcodes - how the design decouples the logic from the shortcode declaration itself, how to implement custom shortcodes
- [x] Notifier
- [x] Twig - functions, filters, and the `HelperInterface`
- [x] Meta-field search
- [x] Testing

**Comment by sdunham** [comment]
FYI, I have a good start on the form docs, and also plan on tackling AJAX unless someone else is already on that.

**Comment by acobster** [comment]
It'd be awesome if you could also document the AJAX stuff. I'm working on some edits to the dev setup and the Admin API atm. Thanks!

**Comment by acobster** [comment]
Considering this good enough. We'll revisit integrations at a later time.
