### ISSUE TITLE
Setting directory cascade paths requires a trailing slash

### ISSUE THREAD

**Issue by sdunham** [sitecrafting/conifer#76]
### Expected behavior

Setting custom directory cascade paths should either not require a trailing slash, or an exception should be thrown if an invalid path is submitted. In either case, the documentation should match the required format

### Actual behavior

When setting custom directory cascade paths for views/js/css, the provided paths need to include a trailing slash, which doesn't match what's included in the [documentation](https://coniferplug.in/site.html#directory-cascades).

### Steps to reproduce behavior

```
// Set a custom js directory path without the trailing slash
$this->set_script_directory_cascade([
	get_template_directory() . '/js',
]);

// Try the get a script URI for a file that exists in /js and throw an exception when it fails
if ($site->get_script_uri('file_that_exists.js') === '') {
	throw new Exception('FOILED AGAIN');
}
```

### What version of WordPress/PHP/Timber/Conifer are you using?

Conifer 0.4

### How did you install Conifer? (for example, via `git clone`, GitHub zip download, Composer/Packagist?)

GitHub zip download

**Comment by acobster** [comment]
@sdunham I believe this is fixed. Can you confirm?

**Comment by acobster** [comment]
@sdunham saw your comment about `trailingslashit`, but I don't really care to add more mocks to the tests just to shave off a few lines of code. Going ahead and closing this.
