### ISSUE TITLE
Composer warning during dev setup

### ISSUE THREAD

**Issue by supersolar** [sitecrafting/conifer#88]
### Behavior
The exact warning message is this: 

_Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error._

It appears we simply need to make the dependency name all lowercase to suppress this error and appease the Composer Gods.

### Steps to reproduce behavior
This warning appeared during dev/contrib installation via Lando.

### How did you install Conifer? (for example, via `git clone`, GitHub zip download, Composer/Packagist?)
My codebase was set up through a GitHub connection in SourceTree.

**Comment by acobster** [comment]
Fixed in 56dbdf4d
